title: MSBA 504
description: Course website for USD MSBA 504: Data Management
theme: just-the-docs

url: https://dcyoung23.github.io/msba504

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
