title: MSBA 504
description: >- # this means to ignore newlines until "baseurl:"
  This is a course website for USD MSBA 504 Data Management
theme: just-the-docs
plugins:
  - jekyll-feed

url: https://dcyoung23.github.io/msba504

search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"