title: MSBA 504
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dcyoung23.github.io/msba504-fa24

###### Build settings
# remote_theme:
theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - .data/  

# Aux link for the upper right navigation
aux_links:
  Canvas: http://canvas.sandiego.edu/
  Gradescope: https://www.gradescope.com/
  Slack: https://usd-msba.slack.com

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Change this to choose where to pick data from
data_folder: fa24

# Config JTD UI elements here
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
#color_scheme: nil

callouts_level: quiet # or loud

callouts:
  highlight:
    title: ⚠️Caution
    color: yellow
  important:
    title: Important
    color: purple
  new:
    title: Discussion
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: ❗Warning
    color: red
  tip:
    title: 💡Tip
    color: green
  acknowledgment:
    title: 🖋️Acknowledgment
    color: blue
  task:
    title: ✅Task
    color: green

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
